### ISSUE TITLE
Asana Inbox issue: inability to select any Inbox item except bottom one

### ISSUE THREAD

**Issue by david7018401** [stefanzweifel/asana-expander-extension#3]
The only issue I've found: When using Asana's Inbox, the plugin presents some bugs. 

If your Inbox view has a lot of items in it, Asana may enter what appears to be an infinite redirect loop (perhaps because the plugin is searching for the "absolute last" item in the Inbox feed?). 

And even if your Inbox only has two items in it, when you click the top one, the plugin seems to force your selection to be the bottom one — and there's no way to fix it .. clicking on the top item again works for a brief second, before the bottom item is selected again.

Love this plugin. Left a 5-star review in the Chrome app store.

**Comment by david7018401** [comment]
Update: It appears the items in the Asana Inbox that may cause the problem are those that have "See more" links in them. 

That is: Comments on an Asana task that appear in Inbox, and are too long for regular display and have the "See more" link, create the bug.

If I just have two items in my Inbox view, and one has a "See more" link, clicking that "See more" link allows me to select _either_ of the two items. That is: It "fixes" the problem.

However, if I don't click the "See more" link, then Chrome will only let me select the Inbox item _with_ the "See more" link; selecting the other item (that does _not_ have a "See more" link) works for a half-second, then auto-jumps to the longer item with the link.

**Comment by stefanzweifel** [comment]
I've noticed that bug too lately. Thanks for the investigation work! 🙏

It sounds the easiest solution would be to disable the extension when you're on the Inbox page. Will add this in the next few days and  tag a release. 
I hope the release will also be propagated through the extensions stores quickly.

**Comment by david7018401** [comment]
Awesome, thank you @stefanzweifel! This plugin is great. Even with the Inbox bug, I'm still encouraging my teams to install it. It's an incredible help! Hopefully we can get the Inbox issue resolved, and then it'll really be A++ stuff. Appreciate you work on this.

**Comment by stefanzweifel** [comment]
@david7018401 Quick update:

I've updated the extension in #4 so it will no longer try to expand links in the Inbox. 
New versions have been submitted to the Chrome Webstore and Firefox Addons.

They should hopefully be reviewed and released in the next few days.
